name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_branches:
    branches: [ main ]
jobs:
   build:
      runs-on: ubuntu-latest

    steps:
   - name: checkout repository
     uses: actions/checkout@v3
     with:
       submodules: 'false'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps --no-progress

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
